stories/css-mixins/section.mdx
system/mixins.css
system/mixins/border.css
system/mixins/section.css
system/section.css

fix: add section mixin, other bug fixes

---

tokens/$themes.json
tokens/Brands/SDS/semantic.json
tokens/Brands/Wesco/semantic.json
tokens/Brands/XpressConnect/semantic.json
tokens/semantic.json

Sds token3

---

stories/css-mixins/typography.mdx
stories/tokens/typography.mdx
system/form.css
system/mixins/typography.css
tokens/semantic.json

fix: css updates for design system changes

---

.github/workflows/semantic-release.yaml

fix: update commit workflow, move to correct position

---

.github/workflows/semantic-release.yaml

fix: don't pull main before committing storybook

---

.gitignore
.stylelintrc
.vscode/settings.json
package-lock.json
package.json
system/form.css
system/icons.css
system/mixins/border.css
system/mixins/colors.css
system/mixins/flex.css
system/mixins/form.css
system/mixins/grid.css
system/mixins/icons.css
system/mixins/resets.css
system/mixins/section.css
system/mixins/shadow.css
system/mixins/spacing.css
system/mixins/typography.css
system/section.css
system/shadows.css
system/typography.css
system/visibility.css

fix: indentation and styllint

---

system/form.css
system/mixins/form.css

fix: use new form tokens

---

.github/workflows/semantic-release.yaml

fix: add postcss build step before release

---

tokens/semantic.json

fix: update subtitle font size

---

.storybook/main.js
docs/stories/spacing/spacing.stories.js
package.json

fix: change storybook build location

---

.github/workflows/semantic-release.yaml

fix: remove build commit from workflow

---

.github/workflows/semantic-release.yaml
docs/Intro.mdx
docs/developers/mixins/borders.mdx
docs/developers/mixins/color.mdx
docs/developers/mixins/icons.mdx
docs/developers/mixins/spacing.mdx
docs/developers/mixins/typography.mdx

fix: broken storybook links

---

tokens/$themes.json
tokens/semantic.json

Adding back of screen- to semantic section of breakpoint sizing.

Sds token8

---

tokens/$themes.json
tokens/semantic.json

Ready for review and developer Design System Tokens

Sds token7

---

.github/workflows/build-system.yml

fix: skip checkout in auto commit CI step

---

docs/developers/buttons.mdx
docs/stories/components/buttons.stories.js
docs/stories/themes/WireExpress.mdx

fix: add button stories, colors for WireExpress

---

package.json
scripts/no-jekyll.js

fix: no jekyll

---

tokens/Components/buttons.json
tokens/Components/form/checkbox.json
tokens/Components/form/switch.json

Sds token14

---

package.json
scripts/no-jekyll.js

fix: remove no jekyll

---

.github/workflows/deploy-storybook.yml

fix: rename TARGET_FOLDER

---

dist/EECOL/theme.css
dist/EECOL/theme.json
dist/EECOL/theme.scss
dist/SDS/theme.css
dist/SDS/theme.json
dist/SDS/theme.scss
dist/Wesco/theme.css
dist/Wesco/theme.json
dist/Wesco/theme.scss
dist/XPC/theme.css
dist/XPC/theme.json
dist/XPC/theme.scss
package-lock.json
tokens/Brands/EECOL/semantic.json
tokens/Brands/Wesco/semantic.json
tokens/Brands/XpressConnect/semantic.json
tokens/Components/form/form.json
tokens/semantic.json

Border fix

---

components/button/button.js
docs/developers/tokens/color.mdx
docs/developers/tokens/forms.mdx
docs/stories/components/buttons.stories.js
docs/stories/themes/EECOL.mdx
docs/stories/themes/WireExpress.mdx

SDS-17 - Fixed issues related to last tokens updates

---

dist/EECOL/theme.css
dist/EECOL/theme.json
dist/EECOL/theme.scss
dist/SDS/theme.css
dist/SDS/theme.json
dist/SDS/theme.scss
dist/Wesco/theme.css
dist/Wesco/theme.json
dist/Wesco/theme.scss
dist/XPC/theme.css
dist/XPC/theme.json
dist/XPC/theme.scss
package-lock.json
tokens/Components/form/select.json
tokens/Components/form/switch.json

fix: switch and select border colors

---

.storybook/preview.js

fix: casing
